Repository azmankudus/hello-hektober, pull requests merged in 2021-10, with the labels that each got.

#2 Hello World in Java
  java/hello-world/HelloWorld.java
Labels: enhancement, hacktoberfest-accepted

#24 Hello World in Golang
  golang/hello_world/hello_world.go
Labels: enhancement, hacktoberfest-accepted

#25 Hello World in Perl
  perl/hello_world/hello_world.pl
Labels: enhancement, hacktoberfest-accepted

#23 Hello World in Ruby
  ruby/hello_world/hello_world.rb
Labels: enhancement, hacktoberfest-accepted

#22 Groovy script
  groovy/hello_world/hello_world.groovy
Labels: enhancement, hacktoberfest-accepted

#13 Hello World in Python
  python/hello-world/hello-world.py
Labels: enhancement

#15 Hello World in Batch script
  batch/hello_world/hello_world.bat
Labels: enhancement

#14 Hello World in Shell Script
  shell/hello_world/hello_world.sh
Labels: enhancement

#26 Create hello_world.cpp
  C++/hello_world/hello_world.cpp
Labels: bug, enhancement, hacktoberfest-accepted

#27 Create hello_world.js
  javascript/hello_world/hello_world.js
Labels: bug, hacktoberfest-accepted

#28 Create hello_world.scala
  scala/hello_world/hello_world.scala
Labels: bug, hacktoberfest-accepted

#29 Create hello_world.rs
  rust/hello_world/hello_world.rs
Labels: bug, hacktoberfest-accepted
